# Generated by Django 5.2 on 2025-04-20 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('overdue', 'Overdue'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
